//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dica.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dica.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Foreign Capital.
        /// </summary>
        public static string AmountofForeignCapital {
            get {
                return ResourceManager.GetString("AmountofForeignCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Lease Fee.
        /// </summary>
        public static string AnnualLeaseFee {
            get {
                return ResourceManager.GetString("AnnualLeaseFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Investment Business.
        /// </summary>
        public static string BusinessType {
            get {
                return ResourceManager.GetString("BusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Currency.
        /// </summary>
        public static string CapitalCurrency {
            get {
                return ResourceManager.GetString("CapitalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship.
        /// </summary>
        public static string Citizenship {
            get {
                return ResourceManager.GetString("Citizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Township.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Company incorporated in Myanmar.
        /// </summary>
        public static string CompanyNameinMyanmar {
            get {
                return ResourceManager.GetString("CompanyNameinMyanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Period.
        /// </summary>
        public static string ConstructionPeriod {
            get {
                return ResourceManager.GetString("ConstructionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Period Type.
        /// </summary>
        public static string ConstructionPeriodType {
            get {
                return ResourceManager.GetString("ConstructionPeriodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Social Responsibility.
        /// </summary>
        public static string CorporateSocialResponsibility {
            get {
                return ResourceManager.GetString("CorporateSocialResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment and Social Impact Assessment.
        /// </summary>
        public static string EnvironmentandSocialImpactAssessment {
            get {
                return ResourceManager.GetString("EnvironmentandSocialImpactAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Lease Term.
        /// </summary>
        public static string ExtendedLeaseTerm {
            get {
                return ResourceManager.GetString("ExtendedLeaseTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Year.
        /// </summary>
        public static string FinancialYear {
            get {
                return ResourceManager.GetString("FinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form of Investment.
        /// </summary>
        public static string FormofInvestment {
            get {
                return ResourceManager.GetString("FormofInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form of Investment .
        /// </summary>
        public static string FormofInvestmentPermit {
            get {
                return ResourceManager.GetString("FormofInvestmentPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of incorporation.
        /// </summary>
        public static string IncorporationPlace {
            get {
                return ResourceManager.GetString("IncorporationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investing Country.
        /// </summary>
        public static string InvestingCountry {
            get {
                return ResourceManager.GetString("InvestingCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place(s) at which investment is permitted.
        /// </summary>
        public static string InvestmentPermittedPlace {
            get {
                return ResourceManager.GetString("InvestmentPermittedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Investor/Promoter.
        /// </summary>
        public static string InvestorName {
            get {
                return ResourceManager.GetString("InvestorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Area.
        /// </summary>
        public static string LandArea {
            get {
                return ResourceManager.GetString("LandArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Area Unit.
        /// </summary>
        public static string LandAreaUnit {
            get {
                return ResourceManager.GetString("LandAreaUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landowner.
        /// </summary>
        public static string Landowner {
            get {
                return ResourceManager.GetString("Landowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြန်မာဘာသာ.
        /// </summary>
        public static string LangMyanmar {
            get {
                return ResourceManager.GetString("LangMyanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease Term.
        /// </summary>
        public static string LeaseTerm {
            get {
                return ResourceManager.GetString("LeaseTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Line1Address {
            get {
                return ResourceManager.GetString("Line1Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 2 Address.
        /// </summary>
        public static string Line2Address {
            get {
                return ResourceManager.GetString("Line2Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Principal Organization.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period for Foreign Capital brought in.
        /// </summary>
        public static string PeriodforForeignCapitalBroughtin {
            get {
                return ResourceManager.GetString("PeriodforForeignCapitalBroughtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period for Foreign Capital Brought in Type.
        /// </summary>
        public static string PeriodforForeignCapitalBroughtinType {
            get {
                return ResourceManager.GetString("PeriodforForeignCapitalBroughtinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Date.
        /// </summary>
        public static string PermitDate {
            get {
                return ResourceManager.GetString("PermitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit No.
        /// </summary>
        public static string PermitNo {
            get {
                return ResourceManager.GetString("PermitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Category.
        /// </summary>
        public static string SectorCategory {
            get {
                return ResourceManager.GetString("SectorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State / Region.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string TaxName {
            get {
                return ResourceManager.GetString("TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount of Capital .
        /// </summary>
        public static string TotalAmountofCapital {
            get {
                return ResourceManager.GetString("TotalAmountofCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total No. of Employee (Foreign).
        /// </summary>
        public static string TotalNoofForeignEmployee {
            get {
                return ResourceManager.GetString("TotalNoofForeignEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total No. of Employee (Local).
        /// </summary>
        public static string TotalNoofLocalEmployee {
            get {
                return ResourceManager.GetString("TotalNoofLocalEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Investment.
        /// </summary>
        public static string TypeOfInvestment {
            get {
                return ResourceManager.GetString("TypeOfInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity of Investment Permit.
        /// </summary>
        public static string ValidityofInvestmentPermit {
            get {
                return ResourceManager.GetString("ValidityofInvestmentPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity of Investment Permit Period Type.
        /// </summary>
        public static string ValidityofInvestmentPermitPeriodType {
            get {
                return ResourceManager.GetString("ValidityofInvestmentPermitPeriodType", resourceCulture);
            }
        }
    }
}
